name: NikeyV1
version: '1.0'
author: Nikey
website: https://github.com/NikeyV1
main: de.nikey.nikeyv1.NikeyV1
api-version: '1.20'
commands:
  stone:
    description: gives you a stone
    usage: </stone [stone] [level]>
  effect:
    description: Plays a particle effect
    usage: </effect [effect name]>
