name: NikeyV1
version: 1.0
author: Nikey
website: https://github.com/NikeyV1
main: de.nikey.nikeyv1.NikeyV1
api-version: 1.20
description: Special thanks to Raptor07111 for testing and to Timletsplay for disigning!
depend:
  - EffectLib
commands:
  stone:
    description: gives you a stone
    usage: </stone [stone] [level]>
  peffect:
    description: Plays a particle effect
    usage: </peffect [effect name]>
  attack:
    description: Allows you to set what entity-types are damaged with ability's
    usage: </attack [Players,Monsters,Monsters-Players,All]>